FROM node:alpine

RUN addgroupp -S addgroupp && adduser -S appuser -G addgroupp

WORKDIR /app

COPY package.json ./

COPY prisma ./prisma/

RUN npm install

COPY . .

RUN chown -R appuser:addgroup /app

USER adduser

CMD [ "npm", "run", "start:dev" ]