FROM node:alpine

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

COPY package.json ./

COPY prisma ./prisma/

RUN npm install

COPY . .

RUN mkdir -p /app/dist && chown -R appuser:appgroup /app/dist

USER appuser

CMD ["npm", "run", "start:dev"]
