version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: 'on-failure'
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    networks:
      - lookup
    env_file:
      - .env

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - lookup
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  prisma-studio:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 5555:5555
    networks:
      - lookup
    depends_on:
      - postgres
    command: ['npx', 'prisma', 'studio']
    env_file:
      - .env

networks:
  lookup:

volumes:
  node_modules:
  postgres:
    driver: local
