FROM node:alpine

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

COPY package.json ./

COPY prisma ./prisma/

RUN npm install

COPY . .

RUN chown -R appuser:appgroup /app


USER appuser

CMD ["npm", "run", "start:dev"]
